const videos = [
  {
    id: 1,
    title: 'React.js - Course (3 Hours)',
    channel: 'Flavio Rocha',
    views: '1 mi de visualizações',
    date: 'há 1 semana',
    avatar: '/images/avatar.png',
    thumb: '/images/thumb1.png',
  },
  {
    id: 2,
    title: 'React.js + Hooks',
    channel: 'Flavio Rocha',
    views: '1 mi de visualizações',
    date: 'há 1 semana',
    avatar: '/images/avatar.png',
    thumb: '/images/thumb2.png',
  },
  {
    id: 3,
    title: 'Material-UI',
    channel: 'Flavio Rocha',
    views: '1 mi de visualizações',
    date: 'há 1 semana',
    avatar: '/images/avatar.png',
    thumb: '/images/thumb3.png',
  },
  {
    id: 4,
    title: 'React.js + Redux',
    channel: 'Flavio Rocha',
    views: '1 mi de visualizações',
    date: 'há 1 semana',
    avatar: '/images/avatar.png',
    thumb: '/images/thumb4.png',
  },
  {
    id: 1,
    title: 'React.js - Course (3 Hours)',
    channel: 'Flavio Rocha',
    views: '1 mi de visualizações',
    date: 'há 1 semana',
    avatar: '/images/avatar.png',
    thumb: '/images/thumb1.png',
  },
  {
    id: 2,
    title: 'React.js + Hooks',
    channel: 'Flavio Rocha',
    views: '1 mi de visualizações',
    date: 'há 1 semana',
    avatar: '/images/avatar.png',
    thumb: '/images/thumb2.png',
  },
  {
    id: 3,
    title: 'Material-UI',
    channel: 'Flavio Rocha',
    views: '1 mi de visualizações',
    date: 'há 1 semana',
    avatar: '/images/avatar.png',
    thumb: '/images/thumb3.png',
  },
  {
    id: 4,
    title: 'React.js + Redux',
    channel: 'Flavio Rocha',
    views: '1 mi de visualizações',
    date: 'há 1 semana',
    avatar: '/images/avatar.png',
    thumb: '/images/thumb4.png',
  },
]

export default videos